apiVersion: v1
kind: Service
metadata:
  name: hello-server-service
spec:
  selector:
    app: hello-server # Serviceを利用したいPodのラベルと一致させる
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # 利用するコンテナが解放しているPortを指定する
